### ISSUE TITLE
1.12.2 Is not supported :(

### ISSUE THREAD

**Issue by armuell** [konwboj/Tumbleweed#1]

**Comment by kragnoth** [comment]
I believe you can fix this by changing acceptedMinecraftVersions = "[1.11,1.12.1]" to acceptedMinecraftVersions = "[1.11,1.13)"

**Comment by ghost** [comment]
yes that is the solution. can someone compile it and share the jar? :D

**Comment by Darkhax** [comment]
I've ported the mod for a friend, here is a zip which contains the mod, along with some other related artifacts. If you just want to play with the mod use `Tumbleweed-Dark-1.12.2-1.0.0.jar` [Tumbleweed-Dark-1.12.2.zip](https://github.com/konwboj/Tumbleweed/files/1346689/Tumbleweed-Dark-1.12.2.zip)

**Comment by ghost** [comment]
wow, thanks darkhax! nice to see you modding :)
i wont reminder enchanting+ this time xD

**Comment by konwboj** [comment]
Updated. Sorry for the wait.
