### ISSUE TITLE
Easy way to customize the mod?

### ISSUE THREAD

**Issue by grandogarndo** [konwboj/Tumbleweed#13]
I want to make a minigame like jeromeasf does to get loot from tumbleweeds, but it seems that you have to type every drop in one by one. is there a way to make this easier? also, how would you spawn them without using dead bushes? could you use air?

**Comment by MYSTICDING0576** [comment]
how do you add modded weapons to it

**Comment by konwboj** [comment]
Sorry for only replying after so long.
Currently, the only way to configure the mod is through the config file. The config file might get expanded in the future.
As for spawning, one can use Minecraft's /summon command to spawn tumbleweeds in custom ways.
