### ISSUE TITLE
Tumbling weeds are too heavy.

### ISSUE THREAD

**Issue by Zarepheth** [konwboj/Tumbleweed#2]
The mod is neat. However, for a balls of brush light enough to be blown by the wind, they are heavy enough to smash crops, reverting them to seeds and farmland to plain dirt. They are also heavy enough to set off wooden pressure plates.

Can you adjust their weight? Or add a config setting for the weight?
I'm not sure if it's related, but I'm also running the Item Physic Full mod - though I think it only affects item drops.

Minecraft 1.12.2
Forge 14.23.1.2555
Tumbleweed 1.11-0.4.4
ItemPhysic 1.4.9

and also a ton of other mods...

**Comment by konwboj** [comment]
Are these mechanics causing any problems? I know they aren't too realistic, but they add a bit of flavor.

**Comment by Zarepheth** [comment]
The mod adds flavor, which is why I installed it. However, when my crops are destroyed by tumbleweeds and my pressure plate activated doors and gates are opened by tumbleweeds, it sort of destroys the desirability of having the tumbleweeds blowing around.

I'm using the Spawn Temple mod, which adds a "safe" place around the world spawn. When starting the game, it also provides an excellent starting place for one's home base. But it has no top, so after I add some pressure plates next to the doors inside the temple, the tumbleweeds land on the pressure plates and open the doors, allowing mobs to enter a place that should be free of mobs. The tumbleweeds can clear a barrier 4 blocks high (or maybe there was a nearby hill...)

As already mentioned, when I've setup fields and planted crops, the tumbleweeds are destroying my plantings, reducing my food harvest. In the early game, this can be a serious problem!

**Comment by konwboj** [comment]
The latest version now includes a Damage Crops config option.
