### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by ProsperCraft** [konwboj/Tumbleweed#3]
https://paste.fedoraproject.org/paste/BRGFG8QwqKNIJOmVsgeEGQ

Modpack used - https://minecraft.curseforge.com/projects/towncraft

**Comment by konwboj** [comment]
Could you check whether it's fixed in the latest version?

**Comment by ProsperCraft** [comment]
No sorry, I removed it from my pack for performance.

**Comment by konwboj** [comment]
Could you reupload the paste if you still have it?

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/8f7331e2d43b79e403c6b78a118bd36a

**Comment by konwboj** [comment]
Thank you!
