### ISSUE TITLE
1.20  update please!

### ISSUE THREAD

**Issue by MotMomet** [konwboj/Tumbleweed#36]
1.20  update please!

**Comment by notstevy** [comment]
If you still need it, I made a fork. 
You can download the update from: https://github.com/notstevy/Tumbleweed/releases/tag/v1.20.1

**Comment by konwboj** [comment]
Updated to 1.20.1

**Comment by MotMomet** [comment]
> If you still need it, I made a fork. You can download the update from: https://github.com/notstevy/Tumbleweed/releases/tag/v1.20.1

lol hello, can you able to make another fork for 1.21? :p
