### ISSUE TITLE
CarryOn incompatibility, no entity name?

### ISSUE THREAD

**Issue by Shivaxi** [konwboj/Tumbleweed#5]
There is a mod called CarryOn that lets you pickup entities such as chests, crafting tables, even mobs that are small enough like pigs, and carry them around.  It's great.  However it causes an issue with this mod here Tumbleweed, because picking up the Tumbleweed causes the Tumbleweed to drop its loot item, but doesn't destroy the Tumbleweed, so you can place it back down and pick it up repeatedly to just infinitely spawn loot items the Tumbleweed would normally drop.

Normally this isn't an issue because Carry On has a blacklist where you can add entities that you do not want to be able to pickup, just in case a confliction like this should occur.  However I cannot for the life of me find the entity ID or name of the Tumbleweed or even what package it's in.  I tried like Tumbleweed:Tumbleweed or Tumbleweed:* for everything, but no matter what the blacklist will not work.

So I guess what I'm really asking is, what in the world is the enitity or package name for the Tumbleweed haha

**Comment by konwboj** [comment]
You've probably found it or given up in frustration, but it could also be tumbleweed.Tumbleweed, tumbleweed:tumbleweed or just Tumbleweed. I think the letter case matters.
