### ISSUE TITLE
Implement max life time?

### ISSUE THREAD

**Issue by xJon** [konwboj/Tumbleweed#7]
Walking around the world, in dry biomes where Tumbleweeds spawn and bounce gracefully, there seems to be multiple points in which they get stuck and add up in a group:
![Screenshot_3](https://user-images.githubusercontent.com/8945347/62271682-8f062600-b47c-11e9-984b-dc5735ff8ffe.png)
Maybe you can implement into the mod a maximum life time if the weed is stuck and cannot move in order to prevent this issue.

**Comment by konwboj** [comment]
Added in 0.4.6
