### ISSUE TITLE
Crash with BOP

### ISSUE THREAD

**Issue by MechanicalOrder** [konwboj/Tumbleweed#8]
Minecraft: 1.12.2
Forge: 14.23.5.2847
Tumbleweed: 0.4.5 for MC 1.11.2/1.12.2
BiomesOPlenty: 1.12.2-7.0.1.2441-universal

During the gameplay i get a "shutting down internal server" then VanillaFix show both mods as the suspected mods, the crash report says the same so i think its an imcompatibility between both mods, here is the crash log:

https://pastebin.com/4scMjZjS

Really hope you can fix this since this is such a cool mod.

**Comment by konwboj** [comment]
Should be fixed in 0.4.6
